name: "Publish release"

on:
  push:
    tags:
      - 'v*'

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3.3.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.9.0
        with:
          distribution: zulu
          java-version: 11
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2.3.3
      - name: gradle publishPlugins
        id: gradle
        run: "./gradlew :publishPlugins"
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
